[features]
seeds = false
skip-lint = false
[programs.devnet]
bindentity = "Ed83sBUkVjtNEbcSnrqtodpVpDwnazHqiqAqncXjWNLZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keys/authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init = "yarn run ts-node --project ./tsconfig.json scripts/init.ts"